void futuresAsync() async {
  // final demo = await Future(() => throw Exception);

  // print(demo);

  try {
    final demo = await Future(() => 5);
    // final demo = await Future(() => throw FormatException);
    print('ðŸŽ‰  $demo');
  } catch (error) {
    print('ðŸ”¥  $error');
  } finally {
    print('âœ…  Complete!');
  }
}
